name: pgmorl
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - numpy
  - setuptools
  - six
  - pillow=7.0.0
  - opencv=3.4.2
  - py-opencv=3.4.2
  - pip=20.0.2
  - matplotlib
  - pyyaml
  - scikit-learn
  - scipy
  - pip:
    - --index-url https://download.pytorch.org/whl/cpu
    - torch
    - torchvision
    - 'gymnasium[mujoco]'
    - ipython
    - tensorboardx
